---
- name: Converge
  hosts: all
  become: true
  vars:
    username: molecule
    docker_data_dir: /opt/services
    ci_mode: true
    tailscale_authkey: ""
    enable_firewall: false

  tasks:
    - name: Apply base role
      ansible.builtin.import_role:
        name: ../../roles/base
