---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Gather passwd database
      ansible.builtin.getent:
        database: passwd

    - name: Gather group database
      ansible.builtin.getent:
        database: group

    - name: Assert configured user exists
      ansible.builtin.assert:
        that:
          - "'molecule' in ansible_facts.getent_passwd"

    - name: Assert expected base packages are installed
      ansible.builtin.assert:
        that:
          - "'git' in ansible_facts.packages"
          - "'gh' in ansible_facts.packages"
          - "'tmux' in ansible_facts.packages"
          - "'curl' in ansible_facts.packages"
          - "'ufw' in ansible_facts.packages"
          - "'fail2ban' in ansible_facts.packages"

    - name: Assert configured user is a member of sudo
      ansible.builtin.assert:
        that:
          - "'sudo' in ansible_facts.getent_group"
          - "'molecule' in ansible_facts.getent_group['sudo'][2].split(',')"

    - name: Assert docker group membership is skipped in ci mode
      ansible.builtin.assert:
        that:
          - "'docker' not in ansible_facts.getent_group or 'molecule' not in ansible_facts.getent_group['docker'][2].split(',')"

    - name: Check configured user home directory
      ansible.builtin.stat:
        path: /home/molecule
      register: user_home_dir

    - name: Assert configured user home directory exists
      ansible.builtin.assert:
        that:
          - user_home_dir.stat.exists
          - user_home_dir.stat.isdir
          - user_home_dir.stat.pw_name == 'molecule'

    - name: Check docker data directory
      ansible.builtin.stat:
        path: /opt/services
      register: docker_data_dir

    - name: Assert docker data directory exists
      ansible.builtin.assert:
        that:
          - docker_data_dir.stat.exists
          - docker_data_dir.stat.isdir
          - docker_data_dir.stat.pw_name == 'molecule'

    - name: Check code-server data directory
      ansible.builtin.stat:
        path: /opt/services/code-server
      register: code_server_dir

    - name: Assert code-server data directory exists
      ansible.builtin.assert:
        that:
          - code_server_dir.stat.exists
          - code_server_dir.stat.isdir
          - code_server_dir.stat.pw_name == 'molecule'

    - name: Check hostname file
      ansible.builtin.command: cat /etc/hostname
      changed_when: false
      register: hostname_file

    - name: Assert hostname matches inventory name
      ansible.builtin.assert:
        that:
          - hostname_file.stdout == inventory_hostname
